### ISSUE TITLE
Add standalone mode?

### ISSUE THREAD

**Issue by K4rakara** [RobinLinus/snapdrop#93]
iOS 13 has added support for app standalone mode, and personally, I think this would perfect SnapDrop. Heres what would need to be changed (more or less):
Add roughly the following to index.html:
```html
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content = "yes">
<meta name="apple-mobile-web-app-title" content="Snapdrop">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Snapdrop">
...
<!--Put this in the start of <body>-->
<div id="background-overlay"></div>
```
Add roughly the following to styles.css:
```css
#background-overlay {
position: fixed;
top: 0;
width: 100vw;
height: 100vh;
margin: 0;
background-color: #fafafa;
z-index: -1;
}
```
Change the following in styles.css:
```css
body {
background: #3367d6;
}
```
Change the following in manifest.json:
```json
{"display": "standalone"}
```

This should(?) add standalone functionality, although it may require some tweaking.

I would have done a pull request, but I couldn't get the server working to test properly :/
(I don't have windows 10 pro/enterprise so i couldn't download the tool)

Hope this helps!
